<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LapanganController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\BookingController;

// Home routes
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/dashboard', [HomeController::class, 'dashboard'])->name('dashboard')->middleware('auth');

// Auth routes (generated by make:auth)
Auth::routes();

// Admin routes
Route::middleware(['auth', 'admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::resource('lapangan', LapanganController::class);
    Route::resource('jadwal', JadwalController::class);
});

// Booking routes
Route::middleware('auth')->group(function () {
    Route::resource('booking', BookingController::class);
});
